# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/advan/mt6789-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter S34NF2 T812,$(TARGET_DEVICE)),)

endif
